version: '3.2'

services:
  app:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      args:
        UID: $U_ID
    ports:
      - 8080:80
    volumes:
      - .docker/apache/000-default_dev.allow_all.conf:/etc/apache2/sites-available/000-default.conf:ro
      - .docker/php/conf/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini:ro
      - .docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./:/var/www
    depends_on:
      - db
      - phpmyadmin
      - mailcatcher

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .docker/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 8082:1080
